version: "3.8"
services:
  mongodb:
    image : mongo
    environment:
      #MONGO_INITDB_ROOT_USERNAME: mongo
      #MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - /home/devuser/mongodb/database:/data/db
    ports:
      - "27018:27017"
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
#      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27018/
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - /home/devuser/postgres/database:/var/lib/postgresql/data